# Generated by Django 5.0.4 on 2024-04-25 01:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GymPlan',
            fields=[
                ('plan_id', models.AutoField(primary_key=True, serialize=False)),
                ('plan_name', models.TextField(max_length=50)),
                ('plan_duration', models.CharField(max_length=50)),
                ('plan_cost', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='UserActivity',
            fields=[
                ('activity_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('user_logged', models.DateField(auto_now=True)),
                ('tracked_weight', models.FloatField()),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserBooking',
            fields=[
                ('booking_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('start_date', models.DateField(auto_now=True)),
                ('plan_type', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='data.gymplan')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
