# Generated by Django 5.0.4 on 2024-04-25 01:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('feedback_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('feedback_msg', models.TextField(max_length=500)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='ClassSchedule',
            fields=[
                ('class_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('class_name', models.CharField(max_length=50)),
                ('class_description', models.TextField(blank=True, max_length=500, null=True)),
                ('class_date', models.DateTimeField()),
                ('tutor_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
